service: crud-client-ebased

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
  environment:
    CLIENT_TABLE: !Ref DiegoTolabaEbasedTable

functions:
    clientCreate:
        name: diegoTolaba-ebased-sls-createClient
        description: 'An API that resturns Created client!'
        handler: src/client/handler/createClient.handler
        memorySize: 128
        events:
          - http: 
              path: clients
              method: post

resources:
  Resources:
    DiegoTolabaEbasedTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "dni"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "dni"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:service}-${self:provider.stage}-ebasedTable