service: crud-client-ebased

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - "sqs:SendMessage" 
        - "sqs:GetQueueUrl"
        - "sns:Publish"
      Resource: "*"
  environment:
    CLIENT_TABLE: !Ref DiegoTolabaEbasedTable
    topicClient: !Ref topicClient
    diegoTolabaEbasedCreateGift: !Ref diegoTolabaEbasedCreateGift
    diegoTolabaEbasedCreateCard: !Ref diegoTolabaEbasedCreateCard

functions:
    clientCreate:
        name: diegoTolaba-ebased-sls-createClient
        description: 'An API that resturns Created client!'
        handler: src/client/handler/createClient.handler
        memorySize: 128
        events:
          - http: 
              path: clients
              method: post
        destinations:
          onSuccess:
            type: sns
            arn: !Ref topicClient

    giftCreate:
        name: diegoTolaba-ebased-createGift
        description: 'Gift client!'
        handler: src/client/handler/createGift.handler
        memorySize: 128
        events:
          - sqs:
              arn:
                Fn::GetAtt:
                  - diegoTolabaEbasedCreateGift
                  - Arn

    cardCreate:
        name: diegoTolaba-ebased-createCard
        description: 'Card client!'
        handler: src/client/handler/createCard.handler
        memorySize: 128
        events:
          - sqs:
              arn:
                Fn::GetAtt:
                  - diegoTolabaEbasedCreateCard
                  - Arn

resources:
  Resources:
    DiegoTolabaEbasedTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "dni"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "dni"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:service}-${self:provider.stage}-ebasedTable

    topicClient:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: topicClient
        TopicName: ${self:service}-${self:provider.stage}-topicClient

    diegoTolabaEbasedCreateGift:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "diegoTolabaEbasedCreateGift"
    
    diegoTolabaEbasedCreateCard:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "diegoTolabaEbasedCreateCard"

    giftTopicClientSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref topicClient
        Endpoint:
          Fn::GetAtt: [diegoTolabaEbasedCreateGift, Arn]
        Protocol: sqs
        RawMessageDelivery: 'false'

    cardTopicClientSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref topicClient
        Endpoint:
          Fn::GetAtt: [diegoTolabaEbasedCreateCard, Arn]
        Protocol: sqs
        RawMessageDelivery: 'false'

    snsToSqsCreateGiftSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Principal: "*"
              Resource: !GetAtt
                - diegoTolabaEbasedCreateGift
                - Arn
              Action: "SQS:SendMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": !Ref topicClient
        Queues:
          - Ref: diegoTolabaEbasedCreateGift

    snsToSqsCreateCardSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Principal: "*"
              Resource: !GetAtt
                - diegoTolabaEbasedCreateCard
                - Arn
              Action: "SQS:SendMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": !Ref topicClient
        Queues:
          - Ref: diegoTolabaEbasedCreateCard