service: crud-client-ebased

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - "sqs:SendMessage" 
        - "sqs:GetQueueUrl"
        - "sns:Publish"
      Resource: "*"
  environment:
    CLIENT_TABLE: !Ref DiegoTolabaEbasedClient
    topicClient: !Ref topicClient
    diegoTolabaEbasedCreateGift: !Ref diegoTolabaEbasedCreateGift
    diegoTolabaEbasedCreateCard: !Ref diegoTolabaEbasedCreateCard

functions:
  - ${file(src/client/functions.yml)}

resources:
  - ${file(src/client/resources.yml)}