Resources:
  DiegoTolabaEbasedClient:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "dni"
          AttributeType: "S"   
      KeySchema:
        -
          AttributeName: "dni"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TableName: ${self:service}-${self:provider.stage}-ebasedClient

  topicClient:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: topicClient
      TopicName: ${self:service}-${self:provider.stage}-topicClient

  diegoTolabaEbasedCreateGift:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "diegoTolabaEbasedCreateGift"
  
  diegoTolabaEbasedCreateCard:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "diegoTolabaEbasedCreateCard"

  giftTopicClientSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref topicClient
      Endpoint:
        Fn::GetAtt: [diegoTolabaEbasedCreateGift, Arn]
      Protocol: sqs
      RawMessageDelivery: 'false'

  cardTopicClientSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref topicClient
      Endpoint:
        Fn::GetAtt: [diegoTolabaEbasedCreateCard, Arn]
      Protocol: sqs
      RawMessageDelivery: 'false'

  snsToSqsCreateGiftSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "allow-sns-messages"
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt
              - diegoTolabaEbasedCreateGift
              - Arn
            Action: "SQS:SendMessage"
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref topicClient
      Queues:
        - Ref: diegoTolabaEbasedCreateGift

  snsToSqsCreateCardSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "allow-sns-messages"
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt
              - diegoTolabaEbasedCreateCard
              - Arn
            Action: "SQS:SendMessage"
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref topicClient
      Queues:
        - Ref: diegoTolabaEbasedCreateCard